---
- name: Build WAR file
  hosts: stage
  become: yes

  tasks:
    - name: Ensure Maven is present
      apt:
       name: maven
       state: present
    - name: Ensure Git is present
      apt:
       name: git
       state: present
    - name: Clone Repo
      git:
       repo: 'https://github.com/Vikas-tm/samplejavacode.git'
       dest: /home
       clone: yes
# нужно выполнить mvn package     
    
- name: install TomCat+deploy WAR
  hosts: web
  become: yes

  tasks:
  - name: Ensure TomCat package is present
    apt:
     name: tomcat
     state: present
# нужно скопировать файл 
  - name: Ensure copy WAR
    copy:
     src: index.html
     dest: /var/www/html

  - name: Ensure TomCat service is started
    service:
     name: tomcat
     state: started
