---
- name: Build WAR file
  hosts: stage
  become: yes
  vars:
    homedir: /home

  tasks:
    - name: Ensure Maven is present
      apt:
       name: maven
       state: present
    - name: Ensure Git is present
      apt:
       name: git
       state: present
    - name: Clone Repo
      git:
       repo: 'https://github.com/Vikas-tm/samplejavacode.git'
       dest: "{{ homedir }}"
       clone: yes
# нужно выполнить mvn package  
    - name: Build sample app
      shell: mvn package chdir="{{ homedir }}/samplejavacode"
# Копирование на web через делегирование stage
#    - name: Copy File War
#      fetch:
#       src: /home/samplejavacode/target/addressbook.war
#       dest: /home
       
    
- name: install TomCat+deploy WAR
  hosts: web
  become: yes

  tasks:
  - name: Ensure TomCat package is present
    apt:
     name: tomcat9
     state: present
  - name: Copy File War
    copy:
     src: /home/samplejavacode/target/addressbook.war
     dest: /var/lib/tomcat9/webapps
     delegate_to: stage
  - name: Ensure TomCat service is started
    service:
     name: tomcat
     state: started
